# version: 2.1
# orbs:
#   python: circleci/python@1.0.0

# executors:
#   self_hosted_runner:
#     machine: true
#     resource_class: gitactionorg/circleci 

# workflows:
#   main:
#     jobs:
#       - python/test:
#           executor: self_hosted_runner 
#           args: '--dev'
#           pkg-manager: pipenv
#           test-tool: pytest
#           post-steps:
#             - store_artifacts:
#                 path: test/test/report.html


version: 2.1
orbs:
  python: circleci/python@1.0.0  

executors:
  self_hosted_runner:
    machine: true
    resource_class: gitactionorg/circleci

jobs:
  run_tests:
    executor: self_hosted_runner
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pipenv  
      - python/test:
          test-tool: pytest  
      - store_artifacts:
          path: test/test/report.html

workflows:
  main:
    jobs:
      - run_tests
